# Generated by Django 4.2.1 on 2023-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comments_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('marital_status', models.SmallIntegerField(default=-1)),
                ('phone', models.TextField(blank=True, null=True)),
                ('change_phone', models.TextField(blank=True, null=True)),
                ('is_verifying_otp', models.SmallIntegerField(default=0)),
                ('check_police', models.SmallIntegerField(default=0)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location', models.TextField()),
                ('password', models.TextField()),
                ('is_super_admin', models.SmallIntegerField(default=0)),
                ('is_admin', models.SmallIntegerField(default=0)),
                ('is_consultant', models.SmallIntegerField(default=0)),
                ('consultant_category_id', models.SmallIntegerField(blank=True, null=True)),
                ('role', models.SmallIntegerField(default=5)),
                ('help_message_id', models.SmallIntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(default=1)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('device_token', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('status', models.SmallIntegerField(default=0)),
                ('language_id', models.SmallIntegerField(default=1)),
                ('remember_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_block', models.IntegerField(default=0)),
            ],
        ),
    ]
