# Generated by Django 4.2.1 on 2023-05-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
